development:
  adapter: postgresql
  encoding: unicode
  database: lol_app_development
  pool: 5
  username: mavanderleest
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: lol_app_test
  pool: 5
  username: mavanderleest
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: lol_app_production
  pool: 5
  username: deployer
  password: